### ISSUE TITLE
Unable to use the offline layers bottom sheet in the landscape view on Android 8.1 (small screen)

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6253]
#### ODK Collect version
the master version f2ce0995dfe77673c8a6bfdef53a0fe2615fa4eb, 2024.2.0 BETA 4
#### Android version
8.1
#### Device used
Nexus 5X
#### Problem description
Unable to use the offline layers bottom sheet in the landscape view – missing list of layers (propbably because there’s not enough space in the screen).
![8landscape](https://github.com/getodk/collect/assets/56479916/c583ad50-c523-4eb3-ad12-c64f11d45c28)

#### Steps to reproduce the problem
1. Open any map and go to the offline layers bottom sheet.
2. Rotate the device so that it’s in the landscape view
#### Expected behavior
There should be enough space to display the list.

**Comment by seadowg** [comment]
@grzesiek2010 @alyblenkin it'd be good to have a think about how we deal with smaller screens like this.

**Comment by alyblenkin** [comment]
@seadowg agreed! I will add this to my backlog. My immediate thoughts are hiding the description with the option to read more so that the bottom sheet doesn't take up the entire screen, but I doubt that will improve it very much. 

I know we've discussed this before, but at some point I think we will need to consider redesigning a lot of the interactions with the map in landscape because the bottom sheet doesn't make it useable. I think we've pushed this out because we don't think it's that common, but I'm going to play around with some ideas and see if we can do something lightweight for now, and what it could look like in the future.

**Comment by alyblenkin** [comment]
I played around with a few ideas in [figma](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=6085-16038&t=jj0E1S2duX63PHI3-1), but want to explore a few other flows before we decide.

**Comment by alyblenkin** [comment]
I think as a first pass to solve the issue, we should focus on making the whole sheet scrollable instead of the layers section. Exploring a different a layout or a side sheet could come next.

**Comment by seadowg** [comment]
> I think as a first pass to solve the issue, we should focus on making the whole sheet scrollable instead of the layers section. Exploring a different a layout or a side sheet could come next.

Maybe both could be so that the "Add Layers" button will still appear at the bottom for larger lists? I'm never sure about nested scrolling...
