### ISSUE TITLE
Uploading many media in central and just after downloading form with this media in collect cause form download fails

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6638]
~~Blocked by #6825~~

#### ODK Collect version
store version, master version 43b17e9b1d5ccd58e192a4dddf890de6641d1f0b
#### Android version
8.1, 11, 15 
#### Device used
Nexus 5X,  Galaxy M12, Pixel 6a
#### Problem description
Uploading many media in central (we tried with 1000 small jpeg files - 88kB) and just after downloading form with this media in collect cause form download fails, we tried it on different phones and results were different, Dominika used Android 8.1 and 10, I've been using Android 11, worst results were on my Android 11, sometimes form download failed for 2h+, on Dominika's Android 10 usually it was downloading quickly, it may also be the difference in network, here are results from our few tests https://docs.google.com/document/d/1QeCPbbSgveMlIk5RiZt5O-EkwKn3J846hnzVSDK9Nls/edit?tab=t.0
#### Steps to reproduce the problem
1. Scan user 1kmedia non entity from project https://test.getodk.cloud/#/projects/513/app-users and wait for form to download
2. Go to https://drive.google.com/drive/folders/1VD36WOajnjWMThpuwPnb-lT4DBkibBDi and download 1k media folder
3. Upload media in 1k media non entity form on central and publish new version of form
4. In collect refresh blank forms and wait
#### Expected behavior
Form download should not fail

**Comment by seadowg** [comment]
Initially, we just want to investigate why this is happening and then discuss whether we should fix it or not.

**Comment by seadowg** [comment]
I've seen some 502 errors back from the server when downloading 100 media file forms manually via "Download form" (rather than with Match Exactly) using the ODK staging server.

**Comment by lognaturel** [comment]
Maybe as part of this or as a separate piece of work, consider whether we could save temp downloaded media so downloads can be resumed.

**Comment by seadowg** [comment]
@WKobus are we able to test this again now to see if it's a duplicate of #6825?

**Comment by WKobus** [comment]
I tried to reproduce the issue but I was able to download 1000 media form without fails after uploading 1000 media files to central (I tried with 4kB and 88kB files) issue #6825 still occurs, so it looks like it was different issue.
